#!/usr/bin/env python3
# Generated by Claude Code (claude.ai/code)
"""Consolidate Nuclei JSONL output into one normalized JSON file.

Walks ``results/<client>/<YYYY-MM>/``, normalizes every ``*.jsonl`` finding
into the seed-document shape, and writes the consolidated array to
``results/<client>/<YYYY-MM>/result-<YYYY-MM-DD>.json``.

Usage:
    python scanner/nuclei_convert_tool.py <client> [--month YYYY-MM]
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

# scanner/ is not a package, so add it to sys.path before importing the
# sibling helper module. Same pattern used by scan.py.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from nuclei_json_converter import consolidate_jsonl_dir  # noqa: E402

# Repo root = parent of scanner/. All filesystem paths are derived from
# here so the script works regardless of the cwd it is invoked from.
REPO_ROOT = Path(__file__).resolve().parent.parent


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    """Define and parse the CLI surface: positional client + optional month."""

    # Argparse setup — mirrors scan.py's positional-client convention so
    # operators have one consistent CLI shape across the scanner tools.
    parser = argparse.ArgumentParser(
        description="Consolidate Nuclei JSONL into one normalized JSON file",
        epilog="Example: python scanner/nuclei_convert_tool.py mdi --month 2026-04",
    )
    parser.add_argument("client", help="client name (matches deployments/<client>/)")
    parser.add_argument(
        "--month",
        default=datetime.now().strftime("%Y-%m"),
        help="scan month YYYY-MM (default: current month)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> None:
    """End-to-end: parse args → resolve dirs → consolidate → write file."""

    args = parse_args(argv)

    # Resolve the input directory using repo-root + client + month. Bail
    # early with a clear message if the directory is missing — most likely
    # the operator typoed the client name or hasn't run a scan yet.
    input_dir = REPO_ROOT / "results" / args.client / args.month
    if not input_dir.is_dir():
        sys.exit(f"Error: {input_dir} does not exist")

    # Pre-flight check: at least one *.jsonl file must exist. An empty
    # directory usually means the scan failed or pointed at the wrong
    # path; better to error than silently emit an empty result file.
    jsonl_files = sorted(input_dir.glob("*.jsonl"))
    if not jsonl_files:
        sys.exit(f"Error: no *.jsonl files found in {input_dir}")

    # Walk every JSONL file in the directory, parse line-by-line, and
    # concatenate into one normalized list (sorted-filename order so
    # output is deterministic).
    consolidated = consolidate_jsonl_dir(input_dir)

    # Compose the output filename from today's date (the run date), and
    # serialize the list as pretty-printed JSON next to the raw JSONL.
    run_date = datetime.now().strftime("%Y-%m-%d")
    output_path = input_dir / f"result-{run_date}.json"
    output_path.write_text(json.dumps(consolidated, indent=2), encoding="utf-8")

    # User-facing summary so the operator immediately knows what got
    # written and how many findings were consolidated.
    print(f"Consolidated {len(consolidated)} finding(s) from {len(jsonl_files)} JSONL file(s)")
    print(f"Output: {output_path}")


if __name__ == "__main__":
    main()
