#!/usr/bin/env python3
# Generated by Claude Code (claude.ai/code)
"""
Local Nuclei scanner CLI.

Usage: python scanner/scan.py <client-name>
Reads targets from: deployments/<client>/targets.txt
Writes results to:  results/<client>/YYYY-MM/
"""

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# scan.py lives inside scanner/ but is invoked from the repo root, so the sibling
# nuclei_helpers module is not on sys.path by default — prepend the scanner dir.
sys.path.insert(0, str(Path(__file__).parent))
from nuclei_helpers import build_nuclei_cmd, load_profiles, run_nuclei  # noqa: E402
from nuclei_json_converter import consolidate_jsonl_dir  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
PROFILES_PATH = Path(__file__).resolve().parent / "profiles" / "profiles.yaml"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="LeanSecurity Nuclei Local Scanner",
        epilog="Example: python scanner/scan.py mdi",
    )
    parser.add_argument("client", help="client name (matches deployments/<client>/)")
    client = parser.parse_args().client
    scan_date = datetime.now().strftime("%Y-%m")

    if not shutil.which("nuclei"):
        sys.exit(
            "Error: nuclei is not installed.\n"
            "Install: brew install nuclei (macOS) or "
            "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest"
        )

    targets = REPO_ROOT / "deployments" / client / "targets.txt"
    if not targets.exists():
        sys.exit(f"Error: deployments/{client}/targets.txt not found")

    # results/<client>/YYYY-MM/ mirrors the cloud storage layout so a single
    # `gcloud storage cp` bridges local output to GCS without any path transformation.
    out_dir = REPO_ROOT / "results" / client / scan_date
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Updating Nuclei templates...")
    subprocess.run(["nuclei", "-update-templates", "-silent"], check=False)  # noqa: S603,S607

    profiles = load_profiles(str(PROFILES_PATH)).get("profiles", {})
    total = len(profiles)

    print(f"Starting scan for {client}...\n")

    for i, (name, profile) in enumerate(profiles.items(), 1):
        print(f"[{i}/{total}] {name}")
        # Output filename convention: {stem}_{YYYY-MM}.jsonl. The stem comes
        # from profiles.yaml `output` field (e.g. "identity.jsonl" → "identity").
        stem = Path(profile.get("output", f"{name}.jsonl")).stem
        output_filename = f"{stem}_{scan_date}.jsonl"
        try:
            cmd = build_nuclei_cmd(
                profile,
                str(targets),
                output_path=output_filename,
                scan_directory=str(out_dir),
            )
            # build_nuclei_cmd does not add -silent; suppress nuclei's per-request progress output.
            cmd.append("-silent")
            run_nuclei(cmd)
        except Exception as exc:  # noqa: BLE001
            # One bad profile must not abort the remaining ones — but surface
            # the failure so a silent run does not look identical to a clean
            # run; operators need to see which profile broke and why.
            print(f"Warning: profile {name} failed: {exc}", file=sys.stderr)

    # Collect every *.jsonl file the scan loop produced, then count total
    # findings by tallying non-blank lines across all files. Each file is
    # opened inside a `with` block so the handle is closed deterministically
    # rather than waiting on garbage collection.
    jsonl_files = sorted(out_dir.glob("*.jsonl"))
    findings = 0
    for jsonl_file in jsonl_files:
        with jsonl_file.open(encoding="utf-8") as handle:
            findings += sum(1 for line in handle if line.strip())

    # Consolidate raw JSONL into the normalized JSON artifact consumed by the SLO
    # tracking component. Failures here are logged but non-fatal — the raw JSONL
    # on disk is the source of truth, so a transformation hiccup should not mask
    # the fact that the scan itself succeeded.
    consolidated_path = None
    try:
        # Walk out_dir, normalize every JSONL line, concatenate to one list.
        consolidated = consolidate_jsonl_dir(out_dir)
        # Filename uses today's date so multiple runs in the same month
        # produce distinct files instead of silently overwriting.
        run_date = datetime.now().strftime("%Y-%m-%d")
        consolidated_path = out_dir / f"result-{run_date}.json"
        consolidated_path.write_text(json.dumps(consolidated, indent=2), encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        # Catch-all is deliberate: report and continue. Operator still
        # sees the scan summary and the raw JSONL is still on disk.
        print(f"\nWarning: failed to write consolidated JSON: {exc}")

    print("\n─── Scan Complete ───")
    print(f"Client:  {client}")
    print(f"Results: results/{client}/{scan_date}/\n")
    print(f"Total findings: {findings}\n")
    for f in jsonl_files:
        size = f.stat().st_size
        print(f"  {f.name}  ({size} bytes)")
    if consolidated_path is not None:
        print(f"\nNormalized: {consolidated_path.name}  ({consolidated_path.stat().st_size} bytes)")
    print("\nTo push results to GCS for Conduit:")
    print(f"  gcloud storage cp {out_dir}/*.jsonl gs://<bucket>/nuclei/{scan_date}/")


if __name__ == "__main__":
    main()
