#!/usr/bin/env python3
# Generated by Claude Code (claude.ai/code)
"""Upload Nuclei scan results to GCS.

Reads ``deployments/<client>/.env`` for GCP project + bucket, verifies the
operator is authenticated to ``gcloud``, then uploads
``results/<client>/<YYYY-MM>/*.jsonl`` to ``<GCS_BUCKET>/<GCS_PREFIX>/<YYYY-MM>/``.

Usage:
    python scanner/upload_to_gcs.py <client> [--month YYYY-MM] [--dry-run]
"""

import argparse
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

# Repo root = parent of scanner/. Every filesystem path is derived from here so
# the script behaves the same regardless of the cwd it is invoked from.
REPO_ROOT = Path(__file__).resolve().parent.parent

# Required and optional keys the .env file must / may declare. Keeping them
# named at module scope so error messages and tests share one source of truth.
REQUIRED_ENV_KEYS = ("GCP_PROJECT", "GCS_BUCKET")
DEFAULT_GCS_PREFIX = "nuclei"


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    """Define and parse the CLI surface: positional client + optional month/dry-run."""

    # Argparse setup — mirrors scan.py and nuclei_convert_tool.py so the three
    # scanner CLIs share one consistent shape (positional client, --month default
    # = current YYYY-MM).
    parser = argparse.ArgumentParser(
        description="Upload Nuclei scan results to GCS",
        epilog="Example: python scanner/upload_to_gcs.py acme --month 2026-04",
    )
    parser.add_argument("client", help="client name (matches deployments/<client>/)")
    parser.add_argument(
        "--month",
        default=datetime.now().strftime("%Y-%m"),
        help="scan month YYYY-MM (default: current month)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the gcloud command that would run, but do not execute it",
    )
    return parser.parse_args(argv)


def load_env(env_path: Path) -> dict[str, str]:
    """Parse a minimal KEY=VALUE .env file into a dict.

    Skips blank lines and ``#`` comments, strips one optional layer of single
    or double quotes around values. Intentionally not pulling in python-dotenv
    for ten lines of parsing — this project keeps its runtime dependency surface
    to pyyaml only.
    """

    # Bail with a clear, actionable message if the file is missing rather than
    # raising a bare FileNotFoundError to the operator.
    if not env_path.is_file():
        sys.exit(f"Error: {env_path} not found (copy deployments/_example/.env.example as a starting point)")

    # Walk every non-blank, non-comment line; split on the first '=' so values
    # containing '=' (e.g. inside a URL) survive intact.
    parsed: dict[str, str] = {}
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            sys.exit(f"Error: malformed line in {env_path}: {raw!r}")
        key, _, value = line.partition("=")
        # Strip a single matching pair of surrounding quotes if present, so
        # GCS_BUCKET="gs://foo" and GCS_BUCKET=gs://foo are equivalent.
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        parsed[key.strip()] = value
    return parsed


def check_gcloud_installed() -> None:
    """Exit with an install hint if gcloud is not on PATH."""

    # shutil.which returns None when the binary is absent; turn that into a
    # human-readable message instead of letting subprocess raise FileNotFoundError.
    if not shutil.which("gcloud"):
        sys.exit("Error: gcloud is not installed.\nInstall: https://cloud.google.com/sdk/docs/install")


def check_gcloud_authenticated() -> str:
    """Return the active GCP account, or exit if none is authenticated."""

    # `gcloud auth list --filter=status:ACTIVE --format=value(account)` prints
    # one line (the active account) when authenticated, and an empty string
    # otherwise. Capture stdout and treat empty-after-strip as "not logged in".
    # ruff anchors S603 on the call line and S607 on the argv line, so both noqa
    # codes are attached to their respective physical lines.
    result = subprocess.run(  # noqa: S603
        ["gcloud", "auth", "list", "--filter=status:ACTIVE", "--format=value(account)"],  # noqa: S607
        capture_output=True,
        text=True,
        check=False,
    )
    account = result.stdout.strip()
    if not account:
        sys.exit("Error: no active gcloud account. Run: gcloud auth login")
    return account


def set_gcloud_project(project: str) -> None:
    """Pin the active gcloud project so the upload writes to the right tenant."""

    # `gcloud config set project <id>` is idempotent and matches the README
    # recipe one-liner. check=True so a failure here aborts before we attempt
    # to upload anything to the wrong project.
    subprocess.run(  # noqa: S603
        ["gcloud", "config", "set", "project", project],  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    )


def build_upload_cmd(jsonl_files: list[Path], destination: str) -> list[str]:
    """Compose the explicit gcloud storage cp argv for the JSONL batch."""

    # Pass each file path explicitly instead of a shell glob so subprocess can
    # run with shell=False — avoids any shell-injection surface from the client
    # name, and gcloud accepts multi-source cp natively.
    return ["gcloud", "storage", "cp", *[str(p) for p in jsonl_files], destination]


def main(argv: Optional[Iterable[str]] = None) -> None:
    """End-to-end: parse args → load env → preflight → upload → summary."""

    args = parse_args(argv)

    # Load per-client env (GCP project + bucket). Per-client placement keeps
    # one client's bucket from leaking into another's run.
    env_path = REPO_ROOT / "deployments" / args.client / ".env"
    env = load_env(env_path)

    # Validate required keys up front so we fail before any external call.
    missing = [k for k in REQUIRED_ENV_KEYS if not env.get(k)]
    if missing:
        sys.exit(f"Error: {env_path} missing required key(s): {', '.join(missing)}")

    project = env["GCP_PROJECT"]
    bucket = env["GCS_BUCKET"].rstrip("/")
    prefix = env.get("GCS_PREFIX", DEFAULT_GCS_PREFIX).strip("/")

    # Sanity-check the bucket form so a typo surfaces here rather than as a
    # cryptic gcloud error mid-upload.
    if not bucket.startswith("gs://"):
        sys.exit(f"Error: GCS_BUCKET must start with 'gs://' (got {bucket!r})")

    # Resolve the source directory and bail if the operator hasn't run a scan
    # for this month or typoed the client/month.
    src_dir = REPO_ROOT / "results" / args.client / args.month
    if not src_dir.is_dir():
        sys.exit(f"Error: {src_dir} does not exist (run scanner/scan.py first?)")

    # At least one *.jsonl must exist; an empty dir usually means a failed scan.
    jsonl_files = sorted(src_dir.glob("*.jsonl"))
    if not jsonl_files:
        sys.exit(f"Error: no *.jsonl files found in {src_dir}")

    # Preflight gcloud: installed + authenticated. Order matters — a missing
    # binary should be reported before we try to invoke it for the auth check.
    check_gcloud_installed()
    account = check_gcloud_authenticated()

    # Compose the destination URI: gs://<bucket>/<prefix>/<month>/ — trailing
    # slash so gcloud copies INTO the directory instead of renaming the first file.
    destination = f"{bucket}/{prefix}/{args.month}/"
    cmd = build_upload_cmd(jsonl_files, destination)

    # Show the plan to the operator before doing anything destructive.
    print(f"Account: {account}")
    print(f"Project: {project}")
    print(f"Source:  {src_dir} ({len(jsonl_files)} jsonl file(s))")
    print(f"Target:  {destination}")

    if args.dry_run:
        # Dry-run path: print the argv we would have executed and exit 0 so
        # operators can sanity-check the resolved paths before committing.
        print("\nDry run — would execute:")
        print("  " + " ".join(cmd))
        return

    # Pin the project so the upload writes to the correct tenant even if the
    # operator's shell is currently pointed elsewhere.
    set_gcloud_project(project)

    # Execute the upload. check=True surfaces non-zero exit as CalledProcessError
    # rather than silently continuing past a partial failure.
    print("\nUploading...")
    subprocess.run(cmd, check=True)  # noqa: S603

    print(f"\nUploaded {len(jsonl_files)} file(s) to {destination}")


if __name__ == "__main__":
    main()
