# Generated by Claude Code
# Tests for per-client profiles.yaml lookup in scan.py (_resolve_profiles_path).

import sys
from pathlib import Path
from unittest.mock import patch

# scanner/ is not a package — add it to sys.path before importing scan
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scanner"))
import scan  # noqa: E402


def test_uses_client_profiles_when_present(tmp_path, monkeypatch):
    # A per-client profiles.yaml exists → resolver returns that path.
    client_dir = tmp_path / "deployments" / "testclient"
    client_dir.mkdir(parents=True)
    client_profiles = client_dir / "profiles.yaml"
    client_profiles.write_text("version: 1\nprofiles: {}\n")

    monkeypatch.setattr(scan, "REPO_ROOT", tmp_path)

    result = scan._resolve_profiles_path("testclient")
    assert result == client_profiles


def test_falls_back_to_global_when_absent(tmp_path, monkeypatch):
    # No per-client profiles.yaml → resolver returns the global default.
    (tmp_path / "deployments" / "testclient").mkdir(parents=True)

    monkeypatch.setattr(scan, "REPO_ROOT", tmp_path)

    result = scan._resolve_profiles_path("testclient")
    assert result == scan._GLOBAL_PROFILES
    assert result.name == "profiles.yaml"
    assert "scanner" in result.parts


def test_scan_main_respects_client_profiles(tmp_path, monkeypatch):
    # main() calls load_profiles with the per-client path when one exists.
    client_dir = tmp_path / "deployments" / "acme"
    client_dir.mkdir(parents=True)
    targets = client_dir / "targets.txt"
    targets.write_text("https://example.com\n")
    client_profiles = client_dir / "profiles.yaml"
    client_profiles.write_text("version: 1\nprofiles: {}\n")

    monkeypatch.setattr(scan, "REPO_ROOT", tmp_path)

    captured_paths: list[str] = []

    def fake_load_profiles(path: str):
        # Record which path was requested, return empty profiles so main() does
        # nothing on the scan loop.
        captured_paths.append(path)
        return {"profiles": {}}

    with (
        patch("scan.shutil.which", return_value="/usr/local/bin/nuclei"),
        patch("scan.subprocess.run"),
        patch("scan.load_profiles", side_effect=fake_load_profiles),
        patch("scan.consolidate_jsonl_dir", return_value=[]),
        patch("scan.list_executed_profiles", return_value=[]),
        patch("scan.build_normalized_document", return_value={}),
        patch("sys.argv", ["scan.py", "acme"]),
    ):
        scan.main()

    assert len(captured_paths) == 1
    assert Path(captured_paths[0]) == client_profiles
