# Generated by Claude Code
"""
Smoke tests for docker/Dockerfile.local.

Builds the image once per pytest session, then exercises entrypoint validation
and a local-mode end-to-end run against an unreachable target. The entire
module skips cleanly when Docker is not available, so CI without Docker still
passes.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

# NUCLEI_VERSION mirrors ARG NUCLEI_VERSION in docker/Dockerfile.local; both
# values must move together. If you bump one, bump the other.
NUCLEI_VERSION = "v3.4.10"
IMAGE_TAG = "leansecurity/nuclei-scanner:test-local"
REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKERFILE = "docker/Dockerfile.local"

# Canonical profile names per scope.md acceptance criteria — every JSONL
# the container produces must start with one of these stems.
CANONICAL_PROFILES = {
    "baseline_web",
    "patch_cve",
    "identity_remote_access",
    "data_protection",
    "transport_security",
    "owasp_top10_core",
    "vuln_monitoring",
}

# Module-level skip — bail out before pytest collects fixtures if Docker is unusable.
if shutil.which("docker") is None:
    pytest.skip("docker CLI not available", allow_module_level=True)
try:
    subprocess.run(  # noqa: S603
        ["docker", "info"],  # noqa: S607
        check=True,
        capture_output=True,
        timeout=5,
    )
except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
    pytest.skip("docker daemon not reachable", allow_module_level=True)


@pytest.fixture(scope="session")
def built_image():
    # Build once per session. Build context is repo root per ADR-007 — the
    # legacy `docker/` build context cannot resolve `COPY scanner/` paths.
    subprocess.run(  # noqa: S603
        [  # noqa: S607
            "docker",
            "build",
            "-f",
            DOCKERFILE,
            "-t",
            IMAGE_TAG,
            "--build-arg",
            f"NUCLEI_VERSION={NUCLEI_VERSION}",
            ".",
        ],
        cwd=REPO_ROOT,
        check=True,
    )
    return IMAGE_TAG


def _run(args, **kwargs):
    # Thin helper so the docker invocation reads consistently across tests.
    return subprocess.run(args, capture_output=True, text=True, **kwargs)  # noqa: S603


def test_nuclei_version_pinned(built_image):
    # Built nuclei must report the pinned version string. Strip the leading 'v'
    # because nuclei -version prints "3.4.10", not "v3.4.10".
    out = _run(
        ["docker", "run", "--rm", "--entrypoint", "nuclei", built_image, "-version"],
        check=True,
    )
    combined = out.stdout + out.stderr
    expected = NUCLEI_VERSION.lstrip("v")
    assert expected in combined, f"expected {NUCLEI_VERSION} in output, got: {combined!r}"


def test_python_version(built_image):
    # Python 3.12.x is the locked base image per ADR-007.
    out = _run(
        ["docker", "run", "--rm", "--entrypoint", "python", built_image, "--version"],
        check=True,
    )
    assert "Python 3.12" in (out.stdout + out.stderr)


def test_profiles_yaml_baked_in(built_image):
    # profiles.yaml must ship inside the image at the canonical path and parse
    # as valid YAML. Runtime download was removed (PROFILES_PATH is gone).
    out = _run(
        [
            "docker",
            "run",
            "--rm",
            "--entrypoint",
            "python",
            built_image,
            "-c",
            "import yaml; "
            "d = yaml.safe_load(open('/app/scanner/profiles/profiles.yaml')); "
            "print(sorted(d['profiles'].keys()))",
        ],
        check=True,
    )
    # Image must contain all seven canonical profiles, no more, no fewer.
    missing = [p for p in CANONICAL_PROFILES if p not in out.stdout]
    assert not missing, f"profiles.yaml missing canonical profiles: {missing}"


def test_missing_client_exits_nonzero(built_image):
    # No CLIENT env var → fail fast with a clear error mentioning CLIENT.
    out = _run(["docker", "run", "--rm", built_image])
    assert out.returncode != 0
    assert "CLIENT" in (out.stdout + out.stderr)


def test_unsupported_cloud_provider_exits_nonzero(built_image):
    # CLOUD_PROVIDER outside the {local,gcp,aws,azure} allowlist → exit 1.
    out = _run(
        [
            "docker",
            "run",
            "--rm",
            "-e",
            "CLIENT=ghost",
            "-e",
            "CLOUD_PROVIDER=oracle",
            built_image,
        ]
    )
    assert out.returncode != 0
    assert "Unsupported" in (out.stdout + out.stderr)


def test_missing_deployment_dir_exits_nonzero(built_image, tmp_path):
    # CLIENT references a directory that doesn't exist on the mounted volume.
    # Local mode validates this at the entrypoint, not deep inside scan.py.
    deployments = tmp_path / "deployments"
    deployments.mkdir()
    out = _run(
        [
            "docker",
            "run",
            "--rm",
            "-e",
            "CLIENT=nonexistent",
            "-v",
            f"{deployments}:/app/deployments:ro",
            built_image,
        ]
    )
    assert out.returncode != 0
    assert "nonexistent" in (out.stdout + out.stderr) or "not found" in (out.stdout + out.stderr)


def test_local_mode_produces_canonical_jsonl_and_normalized_json(built_image, tmp_path):
    # End-to-end smoke: build a tmp deployments tree pointing at port 1 on
    # localhost (always closed, no external network), run the container with
    # UPDATE_TEMPLATES=false (no template fetch), then assert that every
    # JSONL produced uses a canonical profile stem and that result-*.json exists.
    client = "smoketest"
    deployments_root = tmp_path / "deployments"
    client_dir = deployments_root / client
    client_dir.mkdir(parents=True)
    (client_dir / "targets.txt").write_text("http://127.0.0.1:1\n")
    results = tmp_path / "results"
    results.mkdir()

    subprocess.run(  # noqa: S603
        [  # noqa: S607
            "docker",
            "run",
            "--rm",
            "-e",
            f"CLIENT={client}",
            "-e",
            "UPDATE_TEMPLATES=false",
            "-v",
            f"{deployments_root}:/app/deployments:ro",
            "-v",
            f"{results}:/app/results",
            built_image,
        ],
        check=True,
    )

    # Walk results/<client>/YYYY-MM/ for the actual outputs.
    jsonl_files = list((results / client).rglob("*.jsonl"))
    normalized_files = list((results / client).rglob("result-*.json"))
    assert jsonl_files, f"expected at least one *.jsonl under {results / client}"
    assert normalized_files, f"expected result-YYYY-MM-DD.json under {results / client}"

    # Every JSONL filename must be `<canonical>_<YYYY-MM>.jsonl`. Strip the
    # trailing `_YYYY-MM` and assert what remains is a canonical profile name.
    seen_stems = {f.stem.rsplit("_", 1)[0] for f in jsonl_files}
    bad_stems = seen_stems - CANONICAL_PROFILES
    assert not bad_stems, f"non-canonical profile stems detected: {bad_stems}"
    # And no legacy stem may appear — explicit guard against regression.
    legacy = {"identity", "transport", "owasp_top10"}
    assert not (seen_stems & legacy), f"legacy filename stems detected: {seen_stems & legacy}"
