#!/bin/bash
# Generated by Claude Code
# See decisions/ADR-007-python-in-container.md for the architectural shift:
# bash for cloud I/O dispatch, scan.py for scan execution + YAML parsing.
set -euo pipefail

# ─── env validation ───
# CLIENT is required; matches a directory under deployments/<client>/.
: "${CLIENT:?CLIENT env var is required (matches deployments/<client>/)}"
CLOUD_PROVIDER="${CLOUD_PROVIDER:-local}"
UPDATE_TEMPLATES="${UPDATE_TEMPLATES:-true}"

# Allowlist CLOUD_PROVIDER. Anything outside the four supported modes is rejected.
case "${CLOUD_PROVIDER}" in
  local|gcp|aws|azure) ;;
  *) echo "Unsupported CLOUD_PROVIDER: ${CLOUD_PROVIDER}" >&2; exit 1 ;;
esac

# Cloud modes need bucket env; fail fast before doing any work.
if [ "${CLOUD_PROVIDER}" != "local" ]; then
  : "${CONFIG_BUCKET:?CONFIG_BUCKET is required when CLOUD_PROVIDER=${CLOUD_PROVIDER}}"
  : "${RESULTS_BUCKET:?RESULTS_BUCKET is required when CLOUD_PROVIDER=${CLOUD_PROVIDER}}"
fi

# Local mode: deployment dir must already exist on the mounted volume.
if [ "${CLOUD_PROVIDER}" = "local" ]; then
  if [ ! -d "/app/deployments/${CLIENT}" ]; then
    echo "Error: /app/deployments/${CLIENT} not found (mount deployments/ at /app/deployments)" >&2
    exit 1
  fi
fi

TARGETS_PATH="${TARGETS_PATH:-targets/targets.txt}"

# ─── cloud I/O dispatch ───
# download_config: fetch only targets.txt. profiles.yaml is baked into the image
# (PROFILES_PATH env var was removed; runtime download is dead weight).
download_config() {
  case "${CLOUD_PROVIDER}" in
    local)
      # Volume mount at /app/deployments provides targets.txt; nothing to do.
      :
      ;;
    gcp)
      mkdir -p "/app/deployments/${CLIENT}"
      gcloud storage cp "${CONFIG_BUCKET}/${TARGETS_PATH}" \
        "/app/deployments/${CLIENT}/targets.txt"
      ;;
    aws)
      mkdir -p "/app/deployments/${CLIENT}"
      aws s3 cp "s3://${CONFIG_BUCKET}/${TARGETS_PATH}" \
        "/app/deployments/${CLIENT}/targets.txt"
      ;;
    azure)
      mkdir -p "/app/deployments/${CLIENT}"
      az storage blob download --container "${CONFIG_BUCKET}" \
        --name "${TARGETS_PATH}" \
        --file "/app/deployments/${CLIENT}/targets.txt"
      ;;
  esac
}

# upload_results: upload BOTH raw JSONL and consolidated normalized JSON
# (result-YYYY-MM-DD.json), so cloud and local outputs stay symmetric.
upload_results() {
  local results_dir="/app/results/${CLIENT}"
  case "${CLOUD_PROVIDER}" in
    local)
      # Volume mount at /app/results writes results in place; nothing to do.
      :
      ;;
    gcp)
      gcloud storage cp -r "${results_dir}"/* "${RESULTS_BUCKET}/${CLIENT}/"
      ;;
    aws)
      aws s3 cp "${results_dir}/" "s3://${RESULTS_BUCKET}/${CLIENT}/" \
        --recursive --exclude "*" --include "*.jsonl" --include "result-*.json"
      ;;
    azure)
      # Walk both jsonl and result-*.json under YYYY-MM subdirs and upload preserving relative path.
      find "${results_dir}" -type f \( -name "*.jsonl" -o -name "result-*.json" \) | while read -r f; do
        relpath="${f#${results_dir}/}"
        az storage blob upload --container "${RESULTS_BUCKET}" \
          --name "${CLIENT}/${relpath}" --file "${f}"
      done
      ;;
  esac
}

# ─── run ───
download_config

# Template refresh is gated by UPDATE_TEMPLATES so CI/test runs can skip the network call.
if [ "${UPDATE_TEMPLATES}" = "true" ]; then
  nuclei -update-templates -silent
fi

# Single source of truth for scan execution — same scan.py the local CLI runs.
# scan.py self-bootstraps sys.path; no scanner package __init__.py required.
python /app/scanner/scan.py "${CLIENT}"

upload_results

if [ "${CLOUD_PROVIDER}" = "local" ]; then
  echo "Scan complete for ${CLIENT}. Results in /app/results/${CLIENT}/"
else
  echo "Scan complete for ${CLIENT} (provider=${CLOUD_PROVIDER}). Results uploaded to ${RESULTS_BUCKET}/${CLIENT}/"
fi
